[[language]]
name = "c"
file-types = ["h", "c"]
auto-format = true

[[language]]
name = "python"
roots = ["requirements.txt"]
language-servers = ["pyright", "ruff"]
auto-format = true

[language.formatter]
command = "sh"
args = ["-c", "ruff format --config tests/pyproject.toml - | ruff check --config tests/pyproject.toml --fix -"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config]
settings = { run = "onSave" }
